spring:
  application:
    name: "MyApplication for Task Management"  # Sets the name of the Spring application
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/task_management  # JDBC URL for connecting to PostgreSQL
    username: postgres  # PostgreSQL username
    password: password  # PostgreSQL password
    driver-class-name: org.postgresql.Driver  # JDBC driver for PostgreSQL
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # Specifies the Hibernate dialect for PostgreSQL
    show-sql: true  #Print SQL Logs

logging:
  level:
    root: INFO.

jwt:
  secret-key: TXkgU2VjcmV0IEtleSB1c2VkIHRvIGF1dGhlbnRpY2F0ZSB1c2VycyB0byBhY2Nlc3MgdGhlIFRhc2sgTWFuYWdlbWVudCBBcHBsaWNhdGlvbg
#spring.jpa.properties.hibernate.default_schema=task_management
management:
  endpoints:
    web:
      exposure:
        include: "*"